export const DATA = {
  name: "Paulo Lievore Leoni",
  title: "Data Specialist | BI & Analytics Engineer",
  email: "paulo_lievore@hotmail.com",
  phone: "",
  location: "São Paulo, Brazil",
  resumeUrl: "/resume-dataAnalyst.pdf",
  social: {
    github: "",
    linkedin: "https://www.linkedin.com/in/paulo-lievore-leoni-b29ba91a3",
    twitter: "",
    youtube: "",
  },
  about: "I am a BI & Analytics Specialist focused on building scalable and governed data platforms. Currently contributing to the BI structuring of Pluxee Brazil, working with Power BI, Tabular Editor, Azure DevOps, and enterprise semantic modeling. I design intelligent data models, automate deployments using CI/CD pipelines, and ensure governance through structured version control. My goal is to transform complex data ecosystems into reliable, scalable, and decision-driven platforms. I work in agile environments (Scrum and Kanban) with strong ownership and execution mindset.",
  hero: {
    headline: "Building Scalable BI Platforms and Semantic Models that Power Global Decision-Making",
    subheadline: "Enterprise semantic modeling, CI/CD analytics governance, and high-impact data visualization.",
    openToWork: false,
    languages: ["English (Full Professional)", "Spanish (Full Professional)", "Portuguese (Native)"],
  },
  education: [
    {
      institution: "UniCesumar",
      degree: "Bachelor in Software Engineering",
      year: "2020 – 2023",
      score: "",
    },
    {
      institution: "ISAE",
      degree: "MBA – Project Management",
      year: "2022",
      score: "",
    },
  ],
  experience: [
    {
      company: "L3 (Consulting for Pluxee Brazil)",
      companyContext: "Pluxee — global employee benefits (ex-Sodexo), multi-country operations",
      role: "Data Specialist",
      period: "June 2024 – Present | São Paulo, Brazil",
      description: "Enterprise semantic model governance and versioning. Advanced data modeling using Tabular Editor. CI/CD pipeline implementation with Azure DevOps. Corporate dataset standardization. Strategic Power BI training for business users. Data Visualization specialist.",
      current: true,
    },
    {
      company: "Unimed Ponta Grossa",
      role: "Data Analyst",
      period: "June 2022 – June 2024 | Paraná, Brazil",
      description: "Built the complete Data Warehouse architecture from scratch. Designed and implemented ETL pipelines using Python, SQL, and Airflow. Developed advanced PL/SQL procedures, functions, tables, and views. Delivered enterprise BI performance indicators. Applied Scrum methodology in project execution.",
    },
    {
      company: "São Camilo Hospital",
      role: "Data Analyst Assistant",
      period: "January 2021 – July 2021",
      description: "Developed clinical dashboards for hospital operations. SQL data extraction and transformation. IT process improvement initiatives. Clinical data preparation for healthcare teams.",
    },
  ],
  skills: {
    biModeling: [
      "Power BI",
      "Tableau",
      "QlikView",
      "Qlik Sense",
      "Tabular Editor",
      "Enterprise Semantic Modeling",
      "Dimensional Modeling",
      "Data Visualization",
    ],
    dataEngineering: [
      "SQL (Advanced)",
      "PL/SQL",
      "Python",
      "ETL Pipelines",
      "Data Warehouse Architecture",
      "Apache Airflow",
    ],
    devopsGovernance: [
      "Azure DevOps",
      "CI/CD for Analytics",
      "Analytics Governance",
      "Agile (Scrum and Kanban)",
    ],
    tools: ["Excel", "Jupyter Notebook", "VS Code"],
  },
  certifications: [
    "Power BI Desktop: Data Analysis and Visualization",
    "Oracle Data Manipulation (DML)",
    "Pentaho Data Integration (ETL Modeling)",
    "SQL for Managers and Analysts – Analytics and BI",
    "Python for Data Science: Language and NumPy",
    "Python for Data Science: Functions, Packages and Pandas",
    "Machine Learning: Introduction to Classification with Scikit-Learn",
    "Google Analytics – Intelligent Data Collection and Analysis",
    "Business Intelligence: Data Warehouse",
    "Communication Skills",
    "Brazilian Army – Honor Merit",
  ],
  projects: [
    {
      title: "Global Semantic Modeling Platform – Pluxee",
      description: "Designed and implemented scalable enterprise semantic models (Power BI cubes) to establish a single source of truth across the organization. Version-controlled using Azure DevOps. CI/CD automated deployment pipelines. Adopted as a global reference by other country offices. Advanced governance with Tabular Editor. Impact: Standardized BI governance at an international level.",
      tech: ["Power BI", "Tabular Editor", "Azure DevOps", "CI/CD", "Semantic Modeling"],
      link: "#",
      github: "#",
      image: "/images/projects/project-1.jpg",
    },
    {
      title: "Enterprise Data Warehouse – Unimed Ponta Grossa",
      description: "Built the Data Warehouse from the ground up. Dimensional modeling. ETL orchestration using Python and Airflow. SQL performance optimization. Data architecture design. Impact: Structured centralized data intelligence for healthcare operations.",
      tech: ["Python", "Apache Airflow", "SQL", "Dimensional Modeling", "ETL"],
      link: "#",
      github: "#",
      image: "/images/projects/project-2.jpg",
    },
    {
      title: "Semantic Model Validator Tool",
      description: "Developed an internal validation tool to ensure consistency across Power BI semantic models. Automated governance checks. Standard enforcement. CI/CD-ready validation logic. Impact: Increased semantic model reliability and deployment confidence.",
      tech: ["Power BI", "Tabular Editor", "CI/CD", "Governance"],
      link: "#",
      github: "#",
      image: "/images/projects/project-3.jpg",
    },
    {
      title: "Corporate Power BI Training Program",
      description: "Delivered structured Power BI training from beginner to advanced level for more than 300 business users at Pluxee Brazil. Impact: Accelerated data culture maturity and self-service analytics adoption.",
      tech: ["Power BI", "Training", "Data Culture"],
      link: "#",
      github: "#",
      image: "/images/projects/project-4.jpg",
    },
    {
      title: "Real-Time Surgery Monitoring Dashboard – Unimed",
      description: "Designed real-time dashboards to monitor surgery stages. Family members receive real-time progress updates. SMS notifications triggered at each surgical stage. Integrated operational hospital systems. Impact: Increased transparency and improved patient-family experience.",
      tech: ["Power BI", "Real-Time", "Dashboards", "Healthcare"],
      link: "#",
      github: "#",
      image: "/images/projects/project-5.jpg",
    },
  ],
};
